include:
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-base.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-dom0.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-vm.yml'

checks:tests:
  stage: checks
  tags:
    - docker
  variables:
    ENABLE_SLOW_TESTS: 1
    USER: gitlab-runner
  before_script:
    - sudo dnf install -y openssl python3-rpm
    - pip3 install --quiet -r ci/requirements.txt
  script:
    - python3 setup.py build
    - ./run-tests
  after_script:
    - ci/codecov-wrapper

checks:pylint:
  stage: checks
  tags:
    - docker
  before_script:
    - sudo dnf install -y python3-rpm
    - pip3 install --quiet -r ci/requirements.txt
  script:
    - PYTHONPATH=test-packages pylint --extension-pkg-whitelist=rpm,lxml qubesadmin
